USE eliCases;

INSERT INTO inventory VALUES 
('iPhone11 Pro Max', 'Bamboo', 8),
('iPhone11 Pro Max', 'Cherry', 8),
('iPhone11 Pro Max', 'Rosewood', 8),
('iPhone11 Pro Max', 'Walnut', 8),
('iPhone X', 'Bamboo', 10),
('iPhone X', 'Cherry', 11),
('iPhone X', 'Rosewood', 15),
('iPhone X', 'Walnut', 13),
('iPhone XR', 'Bamboo', 10),
('iPhone XR', 'Cherry', 10),
('iPhone XR', 'Rosewood', 10),
('iPhone XR', 'Walnut', 10),
('iPhone XS', 'Bamboo', 14),
('iPhone XS', 'Cherry', 14),
('iPhone XS', 'Rosewood', 8),
('iPhone XS', 'Walnut', 10),
('iPhone XS Max', 'Bamboo', 7),
('iPhone XS Max', 'Cherry', 9),
('iPhone XS Max', 'Rosewood', 7),
('iPhone XS Max', 'Walnut', 7),
('iPhone 8', 'Bamboo', 7),
('iPhone 8', 'Cherry', 14),
('iPhone 8', 'Rosewood', 8),
('iPhone 8', 'Walnut', 4),
('iPhone 8 Plus', 'Bamboo', 1),
('iPhone 8 Plus', 'Cherry', 18),
('iPhone 8 Plus', 'Rosewood', 7),
('iPhone 8 Plus', 'Walnut', 15),
('iPhone 7', 'Bamboo', 7),
('iPhone 7', 'Cherry', 14),
('iPhone 7', 'Rosewood', 8),
('iPhone 7', 'Walnut', 4),
('iPhone 7 Plus', 'Bamboo', 7),
('iPhone 7 Plus', 'Cherry', 18),
('iPhone 7 Plus', 'Rosewood', 7),
('iPhone 7 Plus', 'Walnut', 15),
('iPhone 6', 'Bamboo', 5),
('iPhone 6', 'Cherry', 6),
('iPhone 6', 'Rosewood', 3),
('iPhone 6', 'Walnut', 8),
('iPhone 6S', 'Bamboo', 5),
('iPhone 6S', 'Cherry', 6),
('iPhone 6S', 'Rosewood', 3),
('iPhone 6S', 'Walnut', 8),
('iPhone 6 Plus', 'Bamboo', 14),
('iPhone 6 Plus', 'Cherry', 12),
('iPhone 6 Plus', 'Rosewood', 13),
('iPhone 6 Plus', 'Walnut', 9),
('iPhone 5', 'Bamboo', 8),
('iPhone 5', 'Cherry', 9),
('iPhone 5', 'Rosewood', 9),
('iPhone 5', 'Walnut', 8),
('Samsung Galaxy S20', 'Bamboo', 8),
('Samsung Galaxy S20', 'Cherry', 8),
('Samsung Galaxy S20', 'Rosewood', 8),
('Samsung Galaxy S20', 'Walnut', 8),
('Samsung Galaxy S20 Plus', 'Bamboo', 8),
('Samsung Galaxy S20 Plus', 'Cherry', 8),
('Samsung Galaxy S20 Plus', 'Rosewood', 8),
('Samsung Galaxy S20 Plus', 'Walnut', 8),
('Samsung Galaxy S20 Ultra', 'Bamboo', 8),
('Samsung Galaxy S20 Ultra', 'Cherry', 8),
('Samsung Galaxy S20 Ultra', 'Rosewood', 8),
('Samsung Galaxy S20 Ultra', 'Walnut', 8),
('Samsung Galaxy S10', 'Bamboo', 8),
('Samsung Galaxy S10', 'Cherry', 8),
('Samsung Galaxy S10', 'Rosewood', 8),
('Samsung Galaxy S10', 'Walnut', 8),
('Samsung Galaxy S10e', 'Bamboo', 8),
('Samsung Galaxy S10e', 'Cherry', 8),
('Samsung Galaxy S10e', 'Rosewood', 8),
('Samsung Galaxy S10e', 'Walnut', 8),
('Samsung Galaxy S10 Plus', 'Bamboo', 8),
('Samsung Galaxy S10 Plus', 'Cherry', 8),
('Samsung Galaxy S10 Plus', 'Rosewood', 8),
('Samsung Galaxy S10 Plus', 'Walnut', 8),
('Samsung Galaxy Note 10', 'Bamboo', 8),
('Samsung Galaxy Note 10', 'Cherry', 8),
('Samsung Galaxy Note 10', 'Rosewood', 8),
('Samsung Galaxy Note 10', 'Walnut', 8),
('Samsung Galaxy Note 10 Plus', 'Bamboo', 8),
('Samsung Galaxy Note 10 Plus', 'Cherry', 8),
('Samsung Galaxy Note 10 Plus', 'Rosewood', 8),
('Samsung Galaxy Note 10 Plus', 'Walnut', 8),
('Samsung Galaxy S9', 'Bamboo', 7),
('Samsung Galaxy S9', 'Cherry', 8),
('Samsung Galaxy S9', 'Rosewood', 6),
('Samsung Galaxy S9', 'Walnut', 9),
('Samsung Galaxy S9 Plus', 'Bamboo', 4),
('Samsung Galaxy S9 Plus', 'Cherry', 9),
('Samsung Galaxy S9 Plus', 'Rosewood', 9),
('Samsung Galaxy S9 Plus', 'Walnut', 9),
('Samsung Galaxy 9 Note', 'Bamboo', 5),
('Samsung Galaxy 9 Note', 'Cherry', 7),
('Samsung Galaxy 9 Note', 'Rosewood', 4),
('Samsung Galaxy 9 Note', 'Walnut', 5),
('Samsung Galaxy S8', 'Bamboo', 4),
('Samsung Galaxy S8', 'Cherry', 8),
('Samsung Galaxy S8', 'Rosewood', 5),
('Samsung Galaxy S8', 'Walnut', 5),
('Samsung Galaxy S8 Plus', 'Bamboo', 9),
('Samsung Galaxy S8 Plus', 'Cherry', 10),
('Samsung Galaxy S8 Plus', 'Rosewood', 9),
('Samsung Galaxy S8 Plus', 'Walnut', 8),
('Samsung Galaxy 8 Note', 'Bamboo', 4),
('Samsung Galaxy 8 Note', 'Cherry', 6),
('Samsung Galaxy 8 Note', 'Rosewood', 4),
('Samsung Galaxy 8 Note', 'Walnut', 5),
('Samsung Galaxy S7', 'Bamboo', 8),
('Samsung Galaxy S7', 'Cherry', 11),
('Samsung Galaxy S7', 'Rosewood', 1),
('Samsung Galaxy S7', 'Walnut', 6),
('Samsung Galaxy S7 Edge', 'Bamboo', 4),
('Samsung Galaxy S7 Edge', 'Cherry', 6),
('Samsung Galaxy S7 Edge', 'Rosewood', 0),
('Samsung Galaxy S7 Edge', 'Walnut', 2),
('Samsung Galaxy S6', 'Bamboo', 4),
('Samsung Galaxy S6', 'Cherry', 8),
('Samsung Galaxy S6', 'Rosewood', 5),
('Samsung Galaxy S6', 'Walnut', 5),
('Samsung Galaxy S6 Edge', 'Bamboo', 6),
('Samsung Galaxy S6 Edge', 'Cherry', 7),
('Samsung Galaxy S6 Edge', 'Rosewood', 4),
('Samsung Galaxy S6 Edge', 'Walnut', 4),
('Samsung Galaxy S6 Edge Plus', 'Bamboo', 4),
('Samsung Galaxy S6 Edge Plus', 'Cherry', 6),
('Samsung Galaxy S6 Edge Plus', 'Rosewood', 0),
('Samsung Galaxy S6 Edge Plus', 'Walnut', 2),
('Samsung Galaxy S5', 'Bamboo', 4),
('Samsung Galaxy S5', 'Cherry', 3),
('Samsung Galaxy S5', 'Rosewood', 0),
('Samsung Galaxy S5', 'Walnut', 1),
('Samsung Galaxy S5 Note', 'Bamboo', 3),
('Samsung Galaxy S5 Note', 'Cherry', 6),
('Samsung Galaxy S5 Note', 'Rosewood', 4),
('Samsung Galaxy S5 Note', 'Walnut', 3);